# Generated by Django 6.0.4 on 2026-04-17 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='داشبورد هوشمند تجارتی', max_length=200, verbose_name='نام سایت')),
                ('site_tagline', models.CharField(blank=True, max_length=500, null=True, verbose_name='شعار سایت')),
                ('primary_color', models.CharField(default='#3B82F6', max_length=20, verbose_name='رنگ اصلی')),
                ('secondary_color', models.CharField(default='#10B981', max_length=20, verbose_name='رنگ ثانویه')),
                ('refresh_interval', models.IntegerField(default=300, verbose_name='زمان بروزرسانی (ثانیه)')),
                ('enable_notifications', models.BooleanField(default=True, verbose_name='فعال بودن اعلان\u200cها')),
                ('items_per_page', models.IntegerField(default=25, verbose_name='تعداد آیتم در هر صفحه')),
                ('currency_symbol', models.CharField(default='AFN', max_length=10, verbose_name='نماد ارز')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تنظیمات داشبورد',
                'verbose_name_plural': 'تنظیمات داشبورد',
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'روشن'), ('dark', 'تاریک'), ('auto', 'خودکار')], default='light', max_length=20, verbose_name='تم')),
                ('default_dashboard', models.CharField(choices=[('kpi', 'داشبورد KPI'), ('forecast', 'پیش\u200cبینی مالی'), ('sales', 'گزارش فروش')], default='kpi', max_length=20, verbose_name='داشبورد پیش\u200cفرض')),
                ('email_notifications', models.BooleanField(default=False, verbose_name='اعلان ایمیلی')),
                ('language', models.CharField(default='fa', max_length=10, verbose_name='زبان')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تنظیمات کاربر',
                'verbose_name_plural': 'تنظیمات کاربران',
            },
        ),
    ]
