# Generated by Django 6.0.4 on 2026-04-17 11:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام دسته')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.expensecategory', verbose_name='دسته والد')),
            ],
            options={
                'verbose_name': 'دسته هزینه',
                'verbose_name_plural': 'دسته\u200cهای هزینه',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان هزینه')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='مبلغ')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ هزینه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='receipts/', verbose_name='تصویر رسید')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('approved', 'تأیید شده'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='ثبت کننده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.expensecategory', verbose_name='دسته هزینه')),
            ],
            options={
                'verbose_name': 'هزینه',
                'verbose_name_plural': 'هزینه\u200cها',
                'ordering': ['-date'],
            },
        ),
    ]
