# Generated by Django 6.0.4 on 2026-04-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlySales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transaction_count', models.IntegerField()),
            ],
            options={
                'ordering': ['month'],
            },
        ),
    ]
