# Generated by Django 6.0.4 on 2026-04-17 10:59

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='شماره فاکتور')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ صدور')),
                ('due_date', models.DateField(verbose_name='تاریخ سررسید')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مالیات')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='تخفیف')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='جمع کل')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='مبلغ نهایی')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('sent', 'ارسال شده'), ('paid', 'پرداخت شده'), ('overdue', 'تأخیر'), ('cancelled', 'لغو شده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'فاکتور فروش',
                'verbose_name_plural': 'فاکتورهای فروش',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='SalesTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=50, unique=True, verbose_name='شماره تراکنش')),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ تراکنش')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='مبلغ')),
                ('payment_method', models.CharField(choices=[('cash', 'نقدی'), ('card', 'کارت بانکی'), ('transfer', 'انتقال بانکی'), ('online', 'پرداخت آنلاین')], default='cash', max_length=20, verbose_name='روش پرداخت')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده'), ('refunded', 'بازگشت وجه')], default='completed', max_length=20, verbose_name='وضعیت')),
                ('customer_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام مشتری')),
                ('customer_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تماس')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'تراکنش فروش',
                'verbose_name_plural': 'تراکنش\u200cهای فروش',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='monthlysales',
            options={'ordering': ['-month'], 'verbose_name': 'فروش ماهانه', 'verbose_name_plural': 'فروش\u200cهای ماهانه'},
        ),
        migrations.AddField(
            model_name='monthlysales',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 4, 17, 15, 29, 57, 113905), verbose_name='تاریخ ایجاد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlysales',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='monthlysales',
            name='month',
            field=models.DateField(unique=True, verbose_name='ماه'),
        ),
        migrations.AlterField(
            model_name='monthlysales',
            name='revenue',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='درآمد کل'),
        ),
        migrations.AlterField(
            model_name='monthlysales',
            name='transaction_count',
            field=models.IntegerField(default=0, verbose_name='تعداد تراکنش\u200cها'),
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='توضیحات')),
                ('quantity', models.IntegerField(default=1, verbose_name='تعداد')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='قیمت واحد')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='تخفیف')),
                ('total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='جمع')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.salesinvoice', verbose_name='فاکتور')),
            ],
            options={
                'verbose_name': 'آیتم فاکتور',
                'verbose_name_plural': 'آیتم\u200cهای فاکتور',
            },
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='sales.salestransaction', verbose_name='تراکنش'),
        ),
    ]
